"""
Student A - Test Harness: Run your own iteration experiment
End-to-end workflow for testing hallucination propagation tracking
"""

import ast
import importlib.util
import json
import os
import re
import sys
from datetime import datetime
from typing import List, Dict, Tuple
import subprocess
import tempfile

class IterationTestHarness:
    """
    Simulates multi-turn AI-assisted coding sessions
    Logs each iteration, detects hallucinations, tracks propagation
    """

    def __init__(self, task_id: str, output_dir: str = "./test_outputs"):
        self.task_id = task_id
        self.output_dir = output_dir
        self.iterations = []
        self.hallucinations = []
        self.current_iteration = 0

        os.makedirs(output_dir, exist_ok=True)

    def add_iteration(
        self,
        llm_output: str,
        test_cases: Dict = None,
        prompt: str = None,
        explicit_fix_prompt: bool = False
    ) -> Dict:
        """
        Record a single iteration of LLM output

        Args:
            llm_output: Code generated by LLM
            test_cases: {"test_name": {"code": "...", "expected": "..."}}
            prompt: The prompt sent to LLM
            explicit_fix_prompt: Was this iteration prompted with "fix this"?
        """

        iteration_data = {
            "iteration": self.current_iteration,
            "timestamp": datetime.now().isoformat(),
            "prompt": prompt,
            "explicit_fix_prompt": explicit_fix_prompt,
            "llm_output": llm_output,
            "test_results": {},
            "hallucinations_detected": [],
        }

        # Run tests and capture results
        if test_cases:
            iteration_data["test_results"] = self._run_tests(llm_output, test_cases)

        # Detect hallucinations using multiple methods
        detected = self._detect_hallucinations(llm_output, iteration_data["test_results"])
        iteration_data["hallucinations_detected"] = detected

        self.iterations.append(iteration_data)
        self.current_iteration += 1

        return iteration_data

    def _run_tests(self, code: str, test_cases: Dict) -> Dict:
        """
        Execute tests against generated code
        Returns pass/fail for each test
        """
        results = {}

        for test_name, test_spec in test_cases.items():
            try:
                # Create temporary file with code + test
                with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
                    f.write(code)
                    f.write("\n\n# Test code\n")
                    f.write(test_spec.get("code", ""))
                    f.flush()
                    temp_file = f.name

                # Run the test
                result = subprocess.run(
                    [sys.executable, temp_file],
                    capture_output=True,
                    text=True,
                    timeout=5
                )

                passed = result.returncode == 0
                results[test_name] = {
                    "passed": passed,
                    "output": result.stdout,
                    "error": result.stderr,
                }

                os.unlink(temp_file)

            except subprocess.TimeoutExpired:
                results[test_name] = {
                    "passed": False,
                    "error": "Timeout (infinite loop?)"
                }
            except Exception as e:
                results[test_name] = {
                    "passed": False,
                    "error": str(e)
                }

        return results

    def _detect_hallucinations(self, code: str, test_results: Dict) -> List[Dict]:
        """
        Multi-method hallucination detection:
        1. Static analysis (imports, syntax, obvious errors)
        2. Test failures (logic/semantic errors)
        3. Security scanning
        4. Dependency checking
        """
        detected = []

        # Method 1: Import analysis
        import_hallucinations = self._detect_import_hallucinations(code)
        detected.extend(import_hallucinations)

        # Method 2: Syntax/parsing errors
        syntax_hallucinations = self._detect_syntax_hallucinations(code)
        detected.extend(syntax_hallucinations)

        # Method 3: Failed tests → logic errors
        test_hallucinations = self._detect_test_failures(test_results)
        detected.extend(test_hallucinations)

        # Method 4: Security issues (basic patterns)
        security_hallucinations = self._detect_security_issues(code)
        detected.extend(security_hallucinations)

        return detected

    def _detect_import_hallucinations(self, code: str) -> List[Dict]:
        """Detect missing or non-existent imports"""
        hallucinations = []

        try:
            tree = ast.parse(code)
        except SyntaxError:
            return hallucinations  # reported by the syntax check

        lines = code.split('\n')
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                modules = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
                modules = [node.module]
            else:
                continue

            for module in modules:
                # Check the module can be found without executing the generated code
                if not self._module_exists(module):
                    hallucinations.append({
                        "id": f"h_{self.current_iteration}_import_{len(hallucinations)}",
                        "type": "dependency",
                        "severity": "high",
                        "code_snippet": lines[node.lineno - 1].strip(),
                        "description": f"No module named '{module}'",
                        "location": node.lineno,
                        "detected_by": "import_analysis"
                    })

        return hallucinations

    def _detect_syntax_hallucinations(self, code: str) -> List[Dict]:
        """Detect syntax errors"""
        hallucinations = []

        try:
            compile(code, '<string>', 'exec')
        except SyntaxError as e:
            hallucinations.append({
                "id": f"h_{self.current_iteration}_syntax_{len(hallucinations)}",
                "type": "syntax",
                "severity": "critical",
                "code_snippet": code.split('\n')[e.lineno - 1] if e.lineno else "unknown",
                "description": f"SyntaxError: {e.msg}",
                "location": e.lineno,
                "detected_by": "syntax_check"
            })
        except:
            pass

        return hallucinations

    def _detect_test_failures(self, test_results: Dict) -> List[Dict]:
        """
        Convert test failures to hallucinations.
        Failures with the same root error are reported once, listing every failing test.
        """
        by_error = {}

        for test_name, result in test_results.items():
            if not result.get("passed", False):
                error_line = self._last_error_line(result.get("error", "")) or "Unknown error"
                by_error.setdefault(error_line, []).append(test_name)

        hallucinations = []
        for error_line, test_names in by_error.items():
            halluc_type = "logic"
            name_error = re.match(r"NameError: name '(\w+)' is not defined", error_line)
            if name_error:
                # Undefined name: a missing import if it is a real module, else an invented API
                halluc_type = "dependency" if self._module_exists(name_error.group(1)) else "api"

            hallucinations.append({
                "id": f"h_{self.current_iteration}_test_{len(hallucinations)}",
                "type": halluc_type,
                "severity": "high",
                "code_snippet": error_line,
                "description": f"Tests {', '.join(test_names)} failed: {error_line[:100]}",
                "detected_by": "test_execution"
            })

        return hallucinations

    @staticmethod
    def _last_error_line(stderr: str) -> str:
        """Final line of a traceback, e.g. NameError: name 'json' is not defined"""
        lines = [line.strip() for line in stderr.strip().split('\n') if line.strip()]
        return lines[-1] if lines else ""

    @staticmethod
    def _module_exists(name: str) -> bool:
        try:
            return importlib.util.find_spec(name) is not None
        except (ImportError, ValueError):
            return False

    def _detect_security_issues(self, code: str) -> List[Dict]:
        """Detect basic security anti-patterns"""
        hallucinations = []
        security_patterns = {
            "eval": "eval() allows arbitrary code execution",
            "exec": "exec() allows arbitrary code execution",
            "pickle.loads": "pickle.loads() from untrusted source is unsafe",
            "__import__": "Dynamic imports can load arbitrary modules",
            "os.system": "os.system() can be exploited for command injection",
            "shell=True": "subprocess with shell=True enables command injection",
        }

        for pattern, description in security_patterns.items():
            if pattern in code:
                line_num = next(
                    (i for i, line in enumerate(code.split('\n')) if pattern in line),
                    None
                )
                hallucinations.append({
                    "id": f"h_{self.current_iteration}_sec_{len(hallucinations)}",
                    "type": "security",
                    "severity": "critical",
                    "code_snippet": pattern,
                    "description": description,
                    "location": line_num,
                    "detected_by": "security_pattern_scan"
                })

        return hallucinations

    def track_hallucination_propagation(self) -> Dict:
        """
        Analyze how each hallucination evolves across iterations
        Returns: mapping of hallucination IDs to their lifecycle
        """
        propagation = {}

        # Group hallucinations by approximate type/location across iterations
        for iteration_data in self.iterations:
            for halluc in iteration_data["hallucinations_detected"]:
                halluc_key = f"{halluc['type']}_{halluc.get('code_snippet', 'unknown')[:30]}"

                if halluc_key not in propagation:
                    propagation[halluc_key] = {
                        "type": halluc["type"],
                        "instances": [],
                        "states": []
                    }

                instances = propagation[halluc_key]["instances"]
                if instances and instances[-1]["iteration"] == iteration_data["iteration"]:
                    continue  # already recorded for this iteration
                instances.append({
                    "iteration": iteration_data["iteration"],
                    "description": halluc["description"],
                    "code_snippet": halluc.get("code_snippet", ""),
                    "detected_by": halluc.get("detected_by", ""),
                })

        # Determine final state: resolved if absent from the latest iteration.
        # Still present -> persist if it spans 2+ iterations; a hallucination first
        # seen in the latest iteration has had no chance to be fixed yet.
        last_iteration = self.current_iteration - 1
        for halluc_key, halluc_data in propagation.items():
            instances = halluc_data["instances"]
            if not instances or instances[-1]["iteration"] != last_iteration:
                halluc_data["final_state"] = "resolve"
            elif len(instances) >= 2:
                halluc_data["final_state"] = "persist"
            else:
                halluc_data["final_state"] = "new"

        return propagation

    def generate_test_report(self) -> Dict:
        """Generate comprehensive test report"""

        propagation = self.track_hallucination_propagation()

        # Calculate metrics
        total_hallucinations = sum(
            len(it["hallucinations_detected"]) for it in self.iterations
        )
        unique_hallucinations = len(propagation)
        persistent = sum(
            1 for h in propagation.values() if h["final_state"] == "persist"
        )

        # By type
        by_type = {}
        for halluc_key, halluc_data in propagation.items():
            h_type = halluc_data["type"]
            if h_type not in by_type:
                by_type[h_type] = {"count": 0, "persisting": 0}
            by_type[h_type]["count"] += 1
            if halluc_data["final_state"] == "persist":
                by_type[h_type]["persisting"] += 1

        # Summary
        report = {
            "task_id": self.task_id,
            "num_iterations": self.current_iteration,
            "total_hallucinations_detected": total_hallucinations,
            "unique_hallucinations": unique_hallucinations,
            "persistent_hallucinations": persistent,
            "overall_persistence_rate": persistent / unique_hallucinations if unique_hallucinations > 0 else 0,
            "hallucinations_by_type": by_type,
            "propagation_details": propagation,
            "iterations": self.iterations,
        }

        return report

    def save_report(self, filename: str = None) -> str:
        """Save test report to JSON"""
        if filename is None:
            filename = f"{self.output_dir}/test_report_{self.task_id}.json"

        report = self.generate_test_report()

        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)

        print(f"Report saved: {filename}")
        return filename

    def print_summary(self):
        """Print human-readable summary of test run"""
        report = self.generate_test_report()

        print("\n" + "="*60)
        print(f"TEST REPORT: {report['task_id']}")
        print("="*60)
        print(f"Iterations run: {report['num_iterations']}")
        print(f"Total hallucinations detected: {report['total_hallucinations_detected']}")
        print(f"Unique hallucinations: {report['unique_hallucinations']}")
        print(f"Persistent hallucinations: {report['persistent_hallucinations']}")
        print(f"Persistence rate: {report['overall_persistence_rate']:.2%}")
        print("\nHallucinations by type:")
        for h_type, stats in report['hallucinations_by_type'].items():
            print(f"  {h_type:12} -> {stats['persisting']:2}/{stats['count']:2} persisting")
        print("\n" + "="*60 + "\n")